#pragma once
#define LV_CONF_H 1
#define LV_COLOR_DEPTH 16
#define LV_USE_OS LV_OS_NONE
#define LV_USE_STDLIB_MALLOC LV_STDLIB_BUILTIN
#define LV_MEM_SIZE (2 * 1024 * 1024)
#define LV_USE_LOG 0
#define LV_USE_THORVG_INTERNAL 0
#define LV_USE_THORVG_EXTERNAL 0
#define LV_USE_DRAW_SW 1
#define LV_DRAW_SW_COMPLEX 1
#define LV_DRAW_BUF_STRIDE_ALIGN 1
#define LV_FONT_MONTSERRAT_16 1
#define LV_USE_LINE 1
#define LV_USE_LABEL 1
#define LV_USE_GIF 0
#define LV_USE_LODEPNG 0
#define LV_CACHE_DEF_SIZE 0
#define LV_IMAGE_HEADER_CACHE_DEF_CNT 0
